### ISSUE TITLE
MeanAveragePrecision throw error in DDP mode

### ISSUE THREAD

**Issue by dreaquil** [Lightning-AI/torchmetrics#1144]
## 🐛 Bug

Hi :) ! I am training a detection model (maskrcnn) and it works fine with the MeanAveragePrecision metric in single gpu mode. However, when I activate DDP with 4 GPUs, it throws an error on the first validation phase.

I have investigated and there are more detection labels than there are detections. However, I have gone through and made sure this is never the case when calling update on the metric (I added an assert).
```
  File "/home/andrea/projects/my-project/src/callbacks/detection_metrics.py", line 77, in on_validation_epoch_end
    mean_ap = self.val_mean_ap.compute()
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/metric.py", line 523, in wrapped_func
    value = compute(*args, **kwargs)
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/detection/mean_ap.py", line 908, in compute
    precisions, recalls = self._calculate(classes)
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/detection/mean_ap.py", line 728, in _calculate
    ious = {
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/detection/mean_ap.py", line 729, in <dictcomp>
    (idx, class_id): self._compute_iou(idx, class_id, max_detections)
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/detection/mean_ap.py", line 468, in _compute_iou
    det = [det[i] for i in det_label_mask]
  File "/home/andrea/projects/my-project/.venv/lib/python3.8/site-packages/torchmetrics/detection/mean_ap.py", line 468, in <listcomp>
    det = [det[i] for i in det_label_mask]
IndexError: tuple index out of range
```

Additionally, I stepped through each update here and can confirm that each detection length matches item['labels] and item['scores'].
![image](https://user-images.githubusercontent.com/32460579/178754027-9916fc61-c4d2-4249-8e16-405c79f25191.png)

### To Reproduce

Steps to reproduce the behavior...

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): 0.9.2 with pip
- Python & PyTorch Version (e.g., 1.0): Python 3.8.10, Pytorch 1.12
- Any other relevant information such as OS (e.g., Linux): Linux

**Comment by lspinheiro** [comment]
I have recently hit the same problem, it looks like the error is caused by the following function:

```python
    def _get_safe_item_values(self, item: Dict[str, Any]) -> Union[Tensor, Tuple]:
        if self.iou_type == "bbox":
            boxes = _fix_empty_tensors(item["boxes"])
            if boxes.numel() > 0:
                boxes = box_convert(boxes, in_fmt=self.box_format, out_fmt="xyxy")
            return boxes
        elif self.iou_type == "segm":
            masks = []

            for i in item["masks"].cpu().numpy():
                rle = mask_utils.encode(np.asfortranarray(i))
                masks.append((tuple(rle["size"]), rle["counts"]))

            return tuple(masks)
        else:
            raise Exception(f"IOU type {self.iou_type} is not supported")
```


NOTE: In my case, I'm using `self.iou_type = "segm"`.

The conversion to numpy array seems to cause a mismatch between the size of `gt` and `gt_label_mask` in the following step because `gt_label_mask` is brought back to CPU and will be full batch size, while `gt` wont.

```python
        gt = self.groundtruths[idx]
        det = self.detections[idx]
        gt_label_mask = (self.groundtruth_labels[idx] == class_id).nonzero().squeeze(1)
        det_label_mask = (self.detection_labels[idx] == class_id).nonzero().squeeze(1)

        from loguru import logger

        logger.debug(f"gt device {gt.device}")
        logger.debug(f"gt_label_mask device {gt_label_mask.device}")
        assert len(gt) >= len(
            gt_label_mask
        ), f"Mismatch in ground truth labels. len(gt)={len(gt)}, len(gt_label_mask)={len(gt_label_mask)}, len self.groundtruth_labels[idx]={len(self.groundtruth_labels[idx])}"
```

The error is then thrown at the following step

```python
gt = [gt[i] for i in gt_label_mask]
```

**Comment by mengxi-ascent** [comment]
I met the same problem. The error of unmatched size between `det` and `det_label_mask`, `gt` and `gt_label_mask` will be triggered when:
1. `iou_type` is `segm`
2. distributed mode with multiple GPUs/processes

I looked at the source code and figured out the potential bug. The issue is that when `iou_type` is `segm`, `self.detections` and `self.groudtruths` are the lists of tuples. The parent `Metric` class only perform synchronization for lists of tensors (i.e. type of other internal metric states like `self.detection_scores`) but not the lists of tuples. Since `self.detections` and `self.groundtruths` are not properly synced across ranks. `self.detections` and `self.groundtruths` in each rank will only have a part of the data while other internal metric states have the full data, which causes data unmatched and always `len(self.detections) < len(self.detection_labels)` and `len(self.groundtruth) < len(self.groundtruth_labels)`.

## Verify
I verified the issue as follows:
1. When printing out the length of internal metric states after performing synchronization but before the actual `compute()` in `Metric()` class, we can find `len(self.detections)` and `len(self.groundtruths)` are only `1 / world_size` the full data size while others are the full data size:
https://github.com/Lightning-AI/torchmetrics/blob/v0.11.4/src/torchmetrics/metric.py#L532
```python
            with self.sync_context(
                dist_sync_fn=self.dist_sync_fn,
                should_sync=self._to_sync,
                should_unsync=self._should_unsync,
            ):
               logger.info(
                    f"Rank{dist.get_rank()}: \n"
                    f"detections: {len(self.detections)}, \n"
                    f"detecion_labels: {len(self.detection_labels)}, \n"
                    f"detection_scores: {len(self.detection_scores)}, \n"
                    f"groundtruth: {len(self.groundtruths)}, \n"
                    f"groundtruth_labels: {len(self.groundtruth_labels)}"
                )
                value = compute(*args, **kwargs)
                self._computed = _squeeze_if_scalar(value)
```
In my case where data full size is 1000 and `world_size` is 4, it prints out
```
[2023-04-07 13:33:00,765][INFO] - Rank0: 
detections: 250, 
detecion_labels: 1000, 
detection_scores: 1000, 
groundtruth: 250 
groundtruth_labels: 1000
[2023-04-07 13:33:00,765][INFO] - Rank3: 
detections: 250, 
detecion_labels: 1000, 
detection_scores: 1000, 
groundtruth: 250 
groundtruth_labels: 1000
[2023-04-07 13:33:00,765][INFO] - Rank2: 
detections: 250, 
detecion_labels: 1000, 
detection_scores: 1000, 
groundtruth: 250 
groundtruth_labels: 1000
[2023-04-07 13:33:00,765][INFO] - Rank1: 
detections: 250, 
detecion_labels: 1000, 
detection_scores: 1000, 
groundtruth: 250 
groundtruth_labels: 1000

```
**That verifies `self.detections` and `self.groundtruths` are not properly synced and the lengths are not matched.**

2. The actual synchronization happens in https://github.com/Lightning-AI/torchmetrics/blob/v0.11.4/src/torchmetrics/metric.py#L351 `_sync_dist()`. In `apply_to_collection()`, it only gathers the data if the type of the element in the collection is `Tensor`. For other types, it will remain the same.
```python
        output_dict = apply_to_collection(
            input_dict,
            Tensor,
            dist_sync_fn,
            group=process_group or self.process_group,
        )
```
**That's why `self.detections` and `self.groundtruths` don't get synced.**

## Solution
My solution is to overwrite `_sync_dist()` in `MeanAveragePrecision` to additionally sync `self.detections` and `self.groundtruths` when `iou_type == "segm"`:
```python
    def _sync_dist(
        self, dist_sync_fn: Optional[Callable] = None, process_group: Optional[Any] = None
    ):
        super()._sync_dist(dist_sync_fn=dist_sync_fn, process_group=process_group)

        if self.iou_type == "segm":
            self.detections = self._gather_tuple_list(self.detections, process_group)
            self.groundtruths = self._gather_tuple_list(self.groundtruths, process_group)

    @staticmethod
    def _gather_tuple_list(
        list_to_gather: List[Tuple], process_group: Optional[Any] = None
    ) -> List[Any]:
        world_size = dist.get_world_size(group=process_group)
        list_gathered = [None] * world_size
        dist.all_gather_object(list_gathered, list_to_gather, group=process_group)

        for rank in range(1, world_size):
            assert (
                len(list_gathered[rank]) == list_gathered[0],
                f"Rank{rank} doesn't have the same number of elements as Rank0: "
                f"{list_gathered[rank]} vs. {list_gathered[0]}",
            )
        list_merged = []
        for idx in range(len(list_gathered[0])):
            for rank in range(world_size):
                list_merged.append(list_gathered[rank][idx])

        return list_merged
```
I have verified the metric works properly under distributed mode and `iou_type == "segm"` after fixing.

@lspinheiro the conversion to numpy array doesn't seem to change the size, and always `len(gt) >= len(gt_label_mask)` **if `self.groundtruths` is properly synced**. Note that the bug only happens in the distributed mode with multiple GPUs/processes but not in a single process mode. If the conversion to numpy array is the issue, it most likely happens in the single process mode as well.

@SkafteNicki If possible, I would like to help on the fix but I am not sure about the procedure to get started. It will be great if you can point me to any doc related to the contribute. :smile:

**Comment by SkafteNicki** [comment]
@mengxi-ascent sorry for not getting back to you before.
I have created PR #1763 that implements your proposed solution (together with some other fixes for segmentation mAP).
From my own testing, it seems to be working perfectly. Thanks for sharing :]
