### ISSUE TITLE
Please update conda-forge package to v1.0

### ISSUE THREAD

**Issue by mykappa** [Lightning-AI/torchmetrics#1927]
## 🚀 Feature

Please update the conda-forge package to v1.0. The current version on conda-forge is  v0.11.4 and was updated over 4 months ago.

### Motivation

- Making a conda-only based environment possible
- Being able to use the newest v1.0 features, such as plotting

### Pitch

Please update the conda-forge package to v1.0

### Alternatives

Automate the conda-forge updates

### Additional context

--

**Comment by SkafteNicki** [comment]
Since our feedstock is pointing to the `tar.gz` file:
https://github.com/conda-forge/torchmetrics-feedstock/blob/2fa6b1a24fcfa4af048bef9c622bcf216967c141/recipe/meta.yaml#L9
And that was not uploaded for v1.0.0 and v1.0.1 (see related issue https://github.com/Lightning-AI/torchmetrics/issues/1883 for explaination) it seems to me that we cannot update the conda package. @Borda should we do a quick v1.0.2 to rectify these problems?

**Comment by Borda** [comment]
as Conda relies on `sdist` packages and we had some Pypi issues (see: #1883) we may only re-release all with `post` posix which may be confusing for some other users but unblock this situation :flamingo:

**Comment by SkafteNicki** [comment]
Version 1.0.2 is now available on conda-forge: 
https://anaconda.org/conda-forge/torchmetrics

Sadly v1.0.0 and v1.0.1 will not be available due to reasons pointed out in #1883. 
Closing issue.
