### ISSUE TITLE
Add Perceptual Path Length

### ISSUE THREAD

**Issue by JustinGoheen** [Lightning-AI/torchmetrics#1933]
## 🚀 Feature

Add Perceptual Path Length (PPL) as described in this paper by NVIDIA:

[A Style-Based Generator Architecture for Generative Adversarial Networks](https://arxiv.org/pdf/1812.04948.pdf)

### Motivation

Add additional metrics to support the evaluation of generative models.

### Pitch

Authors from Snap, ETH Zurich, and Carnegie Mellon used PyTorch Lightning in the following paper, but opted to use [a metrics library](https://github.com/toshas/torch-fidelity/tree/master) other than torchmetrics. The only metric the authors needed that does not exist in torchmetrics is PPL.

[Autodecoding Latent 3D Diffusion Models](https://arxiv.org/pdf/2307.05445.pdf)

**Comment by rasbt** [comment]
Sounds great! One thing to add here is that we probably don't want to name it `PPL` (but maybe `PerceptualPathLength`), otherwise it will be confused with the popular perplexity metric
<img width="765" alt="Screenshot 2023-07-24 at 3 43 14 PM" src="https://github.com/Lightning-AI/torchmetrics/assets/5618407/95b96621-67b4-47b9-af17-a749233b2afd">

**Comment by SkafteNicki** [comment]
Hi @JustinGoheen, thanks for raising this issue.
We should definitly have this in torchmetrics. I try to look into it as soon as possible.
And agree with @rasbt that is should be `PerceptualPathLength` and not `PPL`. Usually we try to stick with long named, for example we use `MeanSquaredError` instead of `MSE` even if everyone in the universe agrees what the abbreviation stands for.
