### ISSUE TITLE
May be the paramters of Theil U should change from pred, target to X, y

### ISSUE THREAD

**Issue by Nevermetyou65** [Lightning-AI/torchmetrics#1972]
## 🚀 Feature

In the documentation of `torchmetrics.functional.nominal.theils_u` or even Class `torchmetrics.nominal.TheilsU`, the first two parameters are `pred` and `target` which is kind of _**confusing**_ because this quantity is not symmetric. Maybe change it to `X`  and `y` will be easier to understand? `U(X | y)` instead of `U(pred | target)`. Or is there any specific reason for these present parameters? I really had a hard time figuring it out 🤣

**Comment by SkafteNicki** [comment]
Hi @Nevermetyou65, thanks for raising this issue.
The reason they are called `preds` and `target` is because it is nearly the same terminology we use for all our metrics.
I do not see the value in changing the names, because it is kind of arbitrary what they are called, but we can definitely agree that the documentation can be improved.
