### ISSUE TITLE
A way to track std

### ISSUE THREAD

**Issue by selimfirat** [Lightning-AI/torchmetrics#1999]
## 🚀 Feature

We should implement a way to track std of metrics without any bootrapping. I  am thinking to implement it, but I am not sure whether a wrapper or "reduction="mean_std" parameter for each would be a better choice.

### Motivation

I need to track std of metrics for research purposes. As far as I understood, bootstrapper does not exactly provide this. Easiest for 

### Pitch

A way to track std of a metric. It should log {metric_name} (mean) and {metric_name}_std.

### Alternatives

Bootstrapping for std makes it complicated to describe in a paper. Not sure about its correctness and this is not how it has been done in general.

### Additional context

-

**Comment by SkafteNicki** [comment]
@selimfirat, thanks for raising this issue.
I think this sounds like a fine addition to Torchmetrics, but I am not completely sure what you want to calculate the standard deviation over?
Is it over the metric calculated on different batches / samples?
Is it over different epochs ?

**Comment by selimfirat** [comment]
Thank you for your comment.

My aim is to calculate for different samples, i.e., to calculate mean and std of a metric among test instances.

For example, let's say we want to compute PSNR over images for different compression ratios (different runs). Then x axis can be compression ratios and Y axis is PSNR value. For each of the experiments on the test set, I need a standard deviation or quantile to plot error.

Right now this seems possible to me with bootstrappin, but it is hard to justify its usage. It seems more direct to just compute PSNR for every test image and then output std of them.

I also just realized I can use reduction=None, and take mean/std of it myself. Still, it might be convenient to have something like reduction="mean_and_std".  I am not sure if we would need to implement it for every metric though.

**Comment by SkafteNicki** [comment]
@selimfirat thanks for clarifying what you want.
In that case, I would say that it does not really make sense to implement such a feature for every metric, because many metrics are what is considered *global*. By *global* I mean that the metric cannot be computed on single samples and then averaged over samples. Accuracy is a simple example, as calculating the accuracy on a single samples does not really make sense, only when calculated over many samples. PSNR is on the other hand a *local* metric that does make sense to calculate per sample.

Since `reduction=None` is actually fulfilling your usecase, I think it does not really make sense to add a new `reduction`. Instead I would advice a custom solution like:
```python
class MeanStdPSNR(torchmetrics.image.PeakSignalNoiseRatio):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, reduction=None, **kwargs)

    def compute(self):
        res_per_sample = super().compute()
        return res_per_sample.mean(), res_per_sample.std()
```
if you really want the metric object to take care of all computations.

**Comment by selimfirat** [comment]
Thank you for the clarification. You're right. I later realized reduction=None could be a solution in my previous message. Thank you. This solution is quite elegant.

I am closing this issue as it is resolved and it seems no need for such a feature.
