### ISSUE TITLE
Total sum of squares formula

### ISSUE THREAD

**Issue by vadim0x60** [Lightning-AI/torchmetrics#2373]
In `_r2_score_compute` [r2.py:80](https://github.com/Lightning-AI/torchmetrics/blob/v1.3.1/src/torchmetrics/functional/regression/r2.py#L80-L81) [Total Sum of Squares](https://en.wikipedia.org/wiki/Total_sum_of_squares) is defined as

```
mean_obs = sum_obs / num_obs
tss = sum_squared_obs - sum_obs * mean_obs
```

i.e.

```math
\text{TSS}= \sum_{i=1}^{n}y_{i}^2 - (\sum_{i=1}^{n}y_{i})\bar{y}
```

which is different from the usual formula

```math
\mathrm{TSS}=\sum_{i=1}^{n}\left(y_{i}-\bar{y}\right)^2
```

Am I missing someting? Could this be a mistake

**Comment by SkafteNicki** [comment]
Hi @vadim0x60, thanks for opening this issue.
The two formulations are equal:
```math
TSS = \sum_{i=1}^n (y_i - \bar{y})^2
```
substitute the definition of 
```math
\bar{y} = \frac{\sum_{i=1}^{n} y_i}{n}
```
into the expression we get
```math
TSS = \sum_{i=1}^n (y_i - \frac{1}{n}\sum_{i=1}^{n} y_i)^2
```
then expand the square term
```math
TSS = \sum_{i=1}^{n} \left( y_i^2 - \frac{2y_i}{n} \sum_{i=1}^{n} y_i + \frac{1}{n^2} \sum_{i=1}^{n} y_i^2 \right)
```
Next, distributing the summation across the terms:
```math
TSS = \sum_{i=1}^{n} y_i^2 - \frac{2}{n}\sum_{i=1}^{n} y_i^2 + \frac{1}{n}\sum_{i=1}^{n} y_i^2
```
And finally, simplifying the expression:
```math
TSS = \sum_{i=1}^{n} y_i^2 - \frac{1}{n}(\sum_{i=1}^{n} y_i)^2
```
the last term we can rewrite again by using the definition of the average (in reverse order)
```math
TSS = \sum_{i=1}^{n} y_i^2 - \frac{n^2 \times \bar{y}^2}{n}
```
expand again
```math
TSS = \sum_{i=1}^{n} y_i^2 - \frac{n^2 \times \bar{y} \times \bar{y}}{n}
```
split
```math
TSS = \sum_{i=1}^{n} y_i^2 - \frac{n^2 \times \bar{y}}{n} \times \bar{y}
```
simplify
```math
TSS = \sum_{i=1}^{n} y_i^2 - n \times \bar{y} \times \bar{y}
```
again use the definition of the average to convert into the expression we want
```math
TSS = \sum_{i=1}^{n} y_i^2 - \left( \sum_{i=1}^{n} y_i \right) \bar{y}
```

Hopefully this convince you that the two expressions are equal. The reason for why we use one over the other is kind of lost on me right now, but if I remember correctly one expression is a bit more numerical stable than the other, which is why we have chosen it.

**Comment by vadim0x60** [comment]
Thanks for taking the time to lay this out!
