### ISSUE TITLE
MulticlassAveragePrecision crashes on .compute() if empty

### ISSUE THREAD

**Issue by gui-miotto** [Lightning-AI/torchmetrics#2466]
## 🐛 Bug

As far as I know, if .compute() is used before .update(), just a warning is given. However, `MulticlassAveragePrecision` will also crash.

### To Reproduce

```python
from torchmetrics.classification import MulticlassAveragePrecision, MulticlassAccuracy

MulticlassAccuracy(num_classes=3).compute()  # This is fine. Warning only.
MulticlassAveragePrecision(num_classes=3).compute()  # This is bad. Warning plus error.
```

### Expected behavior

It would be great if `MulticlassAveragePrecision` would behave like the other metrics.

### Environment

- TorchMetrics 1.3.2
- python 3.11.8
- PyTorch 2.2

**Comment by SkafteNicki** [comment]
Hi @gui-miotto, thanks for raising this issue.
In general we do not make any guarantees regarding metrics in torchmetrics what happens when `.compute` is called before `.update` (or `forward`). That the accuracy metric happens to just give a warning and return 0 is just arbitrary. One could make the argument that the accuracy metric should actually crash because the score is clearly undefined if no input have been seen. The same argument is true for average precision score. 

Specifically, for average precision metric you can actually just set the `thresholds` argument and you will get a warning and returned value of zero:
```python
print(MulticlassAveragePrecision(num_classes=3, thresholds=100).compute())  # prints tensor(0.)
```
why does this not crash? Because the default value of `thresholds=None` means that we are dynamically calculating the thresholds values based on input to the metric. No input to the metric no meaningful thresholds to compute. Does it then make sense to when `thresholds=100` to return 0? Not really because, again all the calculations are undefined.

I therefore keep the stance that in general we cannot make sure that metrics where no input is provided can actually succeed with the calculation, which is exactly what the warning we are giving to the user before the program crashes indicates.
