### ISSUE TITLE
 Binary Classification Expected Calibration Error

### ISSUE THREAD

**Issue by Orange2107** [Lightning-AI/torchmetrics#2519]
Hi! It is a useful and powerful tool！
## 🐛 Bug

When I see the source code about Binary Classification ECE, this **function _binary_confusion_matrix_format** which is applied to calculate **pred** and **accurates**.

`def _binary_calibration_error_update(preds: Tensor, target: Tensor) -> Tuple[Tensor, Tensor]:
    confidences, accuracies = preds, target
    return confidences, accuracies`

This function directly takes the **target** as the **accuracies**.
But below the definition of empirical accuracy, it should calculate the accuracy of the model prediction instead of using target directly.

### Expected behavior

So, this function may be is wrong. Maybe it should add some code about that threshold is used to obtain the prediction label of model and the next step is to get accuracy.

**Comment by Orange2107** [comment]
It is my fault，Code is correct，Thank you!

**Comment by QiLi111** [comment]
> It is my fault，Code is correct，Thank you!

Hi, I am confused with this as well. I thought it should be accuracy rather than just counting the number of positive labels, as defined in [1]. Could you please elaborate more about this? Thank you!

C. Guo, G. Pleiss, Y. Sun, and K. Q. Weinberger, “On calibration
of modern neural networks,” in International conference on machine
learning. PMLR, 2017, pp. 1321–1330.
