### ISSUE TITLE
Broken "source" link on torchmetrics.Metric

### ISSUE THREAD

**Issue by michael-s-crouch** [Lightning-AI/torchmetrics#2739]
On https://lightning.ai/docs/torchmetrics/stable/references/metric.html  , the "Source" link on class
torchmetrics.Metric(**kwargs) (near the top of the page) links to https://github.com/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/torchmetrics/metric.py#L51-L1115  , but this is a 404.

**Comment by Borda** [comment]
the problem seems to be with relative path:
`<a class="reference external" href="[https://github.com/Lightning-AI/torchmetrics/blob/master/../../../../../opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/torchmetrics/metric.py#L709-L711](https://github.com/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/torchmetrics/metric.py#L709-L711)"><span class="viewcode-link"><span class="pre">[source]</span></span></a>`
