### ISSUE TITLE
Accuracy for Object detection

### ISSUE THREAD

**Issue by prdai** [Lightning-AI/torchmetrics#568]
## 🚀 Feature

Accuracy for Object detection

### Motivation

I am doing a lot object detection projects and I was thinking it would be a bit easier if there was Accuracy because I am more used to be using accuracy

### Pitch

it is to have a Accuracy for Object detection

### Alternatives

I couldn't find any

### Additional context

None

With best regards,
Ranuga

**Comment by SkafteNicki** [comment]
Hi @Programmer-RD-AI,
Could you please explain how this accuracy for object detection would work differently from the accuracy metric that is already part of `torchmetrics`?

**Comment by OlofHarrysson** [comment]
Hi, I think this is a good idea. It's great that mAP exists now since it's the most common metric for object detection.

I think it would be valuable to also include precision, recall, f1, true positive, false positive, and false negative (true negative doesn't make sense to me in a detection setting). Here's why

1. The suggested metrics are more common and easier to understand. This is great for people with no previous experience in object detection.
2. Some models don't output bounding boxes with confidence scores. For example in text detection it's common to use segmentation models that don't do that.
3. Many models filter their predictions with a confidence threshold. Remaining boxes are often treated "equally" in that they produce a signal to the system, no matter if the confidence is 0.99 or 0.7. These systems would better be evaluated via mentioned metrics.

The calculations needed for this would be very similar to the mAP detection metric.
